// typeIconsMapping.js
import {
  Hotel,
  Cottage,
  Forest,
  Restaurant,
  LocalCafe,
  BeachAccess,
  FilterHdr,
  Park,
  Terrain,
  Waves,
  Spa,
  Fort,
  TempleBuddhist,
  Mosque,
  Church,
  Store,
  Village,
  ShoppingCart,
  LocalMovies,
  TheaterComedy,
  GolfCourse,
  DirectionsBoat,
  Agriculture,
  DirectionsRun,
  Hiking,
  DirectionsBike,
  Explore,
  Museum,
  PhotoLibrary,
  LocalLibrary,
  School,
  Work,
  MusicNote,
  Pool,
  SelfImprovement,
  SportsBar,
  LocalBar,
  Nightlife,
  BakeryDining,
  Yard,
  ParkOutlined,
  Animals,
  EmojiNature,
  Public,
  SportsBaseball,
  SportsSoccer,
  DirectionsBus,
  Flight,
  Train,
  Bridge,
  AccountTree,
  Landscape,
  Apartment,
  Castle,
  AccountBalance,
  Storefront,
} from "@mui/icons-material";

const typeIconsMapping = {
  Hotel: Hotel,
  Resort: Pool,
  Camp: Forest,
  Guesthouse: Cottage,
  Apartment: Apartment,
  Restaurant: Restaurant,
  Cafe: LocalCafe,
  Beach: BeachAccess,
  Dune: FilterHdr,
  Oasis: Park,
  Mountain: Terrain,
  Reef: Waves,
  Spring: Spa,
  Park: ParkOutlined,
  Fortress: Fort,
  Ruins: AccountTree,
  Mosque: Mosque,
  Church: Church,
  Temple: TempleBuddhist,
  Market: Store,
  Village: Village,
  Mall: ShoppingCart,
  Cinema: LocalMovies,
  Theater: TheaterComedy,
  Golf: GolfCourse,
  Marina: DirectionsBoat,
  Stable: Agriculture,
  Track: DirectionsRun,
  Safari: EmojiNature,
  Trail: Hiking,
  Ride: DirectionsBike,
  Expedition: Explore,
  Gallery: PhotoLibrary,
  Museum: Museum,
  Library: LocalLibrary,
  University: School,
  "Co-Working Space": Work,
  Studio: MusicNote,
  Spa: Spa,
  Retreat: SelfImprovement,
  Club: Nightlife,
  Bar: SportsBar,
  Lounge: LocalBar,
  Bakery: BakeryDining,
  Farm: Yard,
  Garden: Park,
  Zoo: Animals,
  Aquarium: EmojiNature,
  Observatory: Public,
  Stadium: SportsBaseball,
  Arena: SportsSoccer,
  Port: DirectionsBus,
  Airport: Flight,
  Station: Train,
  Bridge: Bridge,
  Monument: Landscape,
  Tower: AccountBalance,
  Square: Landscape,
  Fountain: Spa,
  Castle: Castle,
  Palace: AccountBalance,
  Bazaar: Storefront,
};

export default typeIconsMapping;
